apiDir: "../headless-site-api/src/main/java"
apiPackagePath: "com.liferay.headless.site"
application:
    baseURI: "/headless-site"
    className: "HeadlessSiteApplication"
    name: "Liferay.Headless.Site"
author: "Rub√©n Pulido"
clientDir: "../headless-site-client/src/main/java"
forcePredictableOperationId: true
generateBatch: false
generateGraphQL: false